AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Slackronym Lambda function & URL

Globals:
  Function:
    Timeout: 3

Resources:
  SlackronymFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: slackronym/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE